apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: taskflow-production
spec:
  selector:
    app: taskflow
    tier: backend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: taskflow-production
spec:
  selector:
    app: taskflow
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30090
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: taskflow-production
spec:
  selector:
    app: taskflow
    tier: cache
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
